---
all:
  children:
    linux_servers:
      hosts:
        server-01: { ansible_host: 192.0.2.101 }
        server-02: { ansible_host: 192.0.2.102 }
        server-03: { ansible_host: 192.0.2.103 }
        server-04: { ansible_host: 192.0.2.104 }
        server-05: { ansible_host: 192.0.2.105 }
        server-06: { ansible_host: 192.0.2.106 }
        server-07: { ansible_host: 192.0.2.107 }
        server-08: { ansible_host: 192.0.2.108 }
        server-09: { ansible_host: 192.0.2.109 }
        server-10: { ansible_host: 192.0.2.110 }
        server-11: { ansible_host: 192.0.2.111 }
        server-12: { ansible_host: 192.0.2.112 }
        server-13: { ansible_host: 192.0.2.113 }
        server-14: { ansible_host: 192.0.2.114 }
        server-15: { ansible_host: 192.0.2.115 }
        server-16: { ansible_host: 192.0.2.116 }
        server-17: { ansible_host: 192.0.2.117 }
        server-18: { ansible_host: 192.0.2.118 }
        server-19: { ansible_host: 192.0.2.119 }
        server-20: { ansible_host: 192.0.2.120 }
