---
- name: 공통 OS 정보 준비
  ansible.builtin.import_tasks: common.yml

- name: 콘솔 호스트명 비노출 및 SSH 상세 인증 로그 적용
  ansible.builtin.import_tasks: components/login_warning.yml

- name: NTP 시간 동기화 적용
  ansible.builtin.import_tasks: components/ntp.yml

- name: 로컬 로그 보존 적용
  ansible.builtin.import_tasks: components/local_logging.yml

- name: audit 감사 규칙 적용
  ansible.builtin.import_tasks: components/audit.yml

- name: 중앙 로그 전송 적용
  ansible.builtin.import_tasks: components/central_logging.yml
